# Generated by Django 5.0.4 on 2024-04-05 18:28

import db_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0002_category_alter_good_name_good_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(validators=[db_manager.models.PositiveFloatValidator()]),
        ),
    ]
