# Generated by Django 5.0.4 on 2024-04-06 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manager', '0005_remove_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
